#!/usr/bin/env python
#
# monwalkd      This shell script takes care of starting and stopping
#               the Monitoring snmpwalk Daemon (monwalkd).
#
# chkconfig: 345 99 01
# description:  This daemon gather recent traffic data from snmpwalk
#		and send to a database on another server about every 2 minutes.
# processname: monwalkd
# pidfile: /var/run/monwalkd.pid

import sys, time

#print sys.path

sys.path.append("/opt/monwalkd/lib")
import setting

from myDaemon import monwalkd

if __name__ == "__main__":
	#print "hello"
	#print sys.argv
	if len(sys.argv) >=2:
		if sys.argv[-1]=='debug':
			isDebugMode=True
		else:
			isDebugMode=False

		logFile=setting.LOG_PATH+'monwalkd.log'

		d = monwalkd('/var/run/monwalkd.pid','monwalkd',stdout=logFile,stderr=logFile,isDebugMode=isDebugMode)
		
		if 'start' == sys.argv[1]:
			#d.waitLocalPort()
			d.start()
		elif 'stop' == sys.argv[1]:
			d.stop()
		elif 'restart' == sys.argv[1]:
			d.stop()
			#d.waitLocalPort()
			d.start()
		elif 'status' == sys.argv[1]:
			d.status()
		elif 'clearlog' == sys.argv[1]:
			open(logFile,'w').close()
		else:
			print "Unknown command"
			sys.exit(2)
		sys.exit(0)
	else:
		print "usage: monwalkd {start|stop|restart|status|clearlog} [debug]"
		sys.exit(2)
