#!/usr/bin/env python
#
# monapid       This shell script takes care of starting and stopping
#               Application Programming Interface Daemon of monitoring
#		system (monapid).
#
# chkconfig: 345 99 01
# description:  This daemon will open 8080 port to response json.
#		It will connect to many databases.
# processname: monapid
# pidfile: /var/run/monapid.pid

import sys, time

#print sys.path

sys.path.append("/opt/monapid/lib")
import setting

from myDaemon import monapid

if __name__ == "__main__":
	#print "hello"
	#print sys.argv
	if len(sys.argv) >=2:
		if sys.argv[-1]=='debug':
			isDebugMode=True
		else:
			isDebugMode=False

		logFile=setting.LOG_PATH+'monapid.log'

		d = monapid('/var/run/monapid.pid','monapid',stdout=logFile,stderr=logFile,isDebugMode=isDebugMode)
		
		if 'start' == sys.argv[1]:
			d.start()
		elif 'stop' == sys.argv[1]:
			d.stop()
		elif 'restart' == sys.argv[1]:
			d.stop()
			d.start()
		elif 'status' == sys.argv[1]:
			d.status()
		elif 'clearlog' == sys.argv[1]:
			open(logFile,'w').close()
		else:
			print "Unknown command"
			sys.exit(2)
		sys.exit(0)
	else:
		print "usage: monapid {start|stop|restart|status|clearlog} [debug]"
		sys.exit(2)
